### ISSUE TITLE
`tidy` and `glance` methods

### ISSUE THREAD

**Issue by vincentarelbundock** [lrberge/fixest#21] opened 2020-05-30 13:32 UTC
"tidiers" are a set of methods defined by the `generics` and `broom` packages to extract information from model objects in a standardized fashion.

https://broom.tidymodels.org/

A `tidy.fixest` method would return a data.frame with one row per term, and columns with standard names: term, estimate, std.error, statistic, p.value, conf.low, conf.high

A `glance.method` method would return a data.frame with a single row, and columns for the most important goodness-of-fit statistics and model characteristics.

There are two main benefits of supplying tidiers in a package:

1. Users do not have to learn the idiosyncrasies of the internal structure of each kind of model object they use. This allows analysts to interact with a bunch of models programmatically in a predicable fashion.
2. External packages which rely on `tidy` and `glance`, [such as my `modelsummary` package](https://vincentarelbundock.github.io/modelsummary), would support `fixest` automatically.

As a stopgap measure, I have implemented `tidy` and a `glance` methods inside `modelsummary`: https://github.com/vincentarelbundock/modelsummary/blob/master/R/tidiers.R#L106

Ideally, these methods would be ported over to `fixest` itself, as is recommended by the `broom` and `tidymodels` conventions.

Would you be interested in a Pull Request to add these methods to your package?

This would allow stuff like this:

```r
remotes::install_github('vincentarelbundock/modelsummary')

library(fixest)
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/plm/EmplUK.csv'
dat <- read.csv(url)

mod <- list()
mod[[1]] <- lm(wage ~ emp + capital, dat)
mod[[2]] <- feols(wage ~ emp + capital | firm, dat)
mod[[3]] <- feols(wage ~ emp + capital | year, dat)
mod[[4]] <- feols(wage ~ emp + capital | firm + year, dat)

msummary(mod, title = "tidy and glance functions allow easy programmatic manipulation of fixest objects. In turn, this allows packages like modelsummary to support fixest out-of-the-box.")
```

Which produces an HTML or a LaTeX table like this one:

![latextable](https://imgur.com/0sqQRh0.png)

**Comment by karldw** [comment] 2020-05-30 22:02
Hey @vincentarelbundock, I hope I catch you before you sink a bunch of time into writing _broom_-compatible `tidy` and `glance` methods for _fixest_. I have a PR in progress for the _broom_ repository (https://github.com/tidymodels/broom/pull/793). 
See also #2. Feel free to pull anything out of the _broom_ PR that would be useful in _modelsummary_.


@lrberge, maybe it's also worth mentioning that these methods could be provided by _fixest_ with a dependency on [_generics_](https://cran.r-project.org/web/packages/generics/index.html), without depending on  _broom_. (If you wanted to go that route, it might still be convenient to use [_modeltests_](https://github.com/alexpghayes/modeltests) for tests.) I'm still happy to continue with my PR on the _broom_ repo.

**Comment by vincentarelbundock** [comment] 2020-05-30 22:33
Thanks for letting me know @karldw 

I have already implemented a stopgap version inside `modelsummary`, but your version seems much better than my quick and dirty one. I'll remove it once your work gets accepted to either `broom` or `fixest` itself.

One thing I did different was to add a new column for every fixed effect variables. That's useful for `modelsummary` because it gives the result above automatically. But I'm not sure `broom` would want `glance` output of varying dimensions depending on the specific model.

**Comment by lrberge** [comment] 2020-06-01 14:54
Hi, everyone!

@vincentarelbundock, developing broom methods was an early request from @karldw. I really think it's a great idea with a lot of value, but I just wasn't in favor of putting them into `fixest` because I would like to keep the package as free as possible from imports.
Regarding the fixed-effects information issue, I don't know if `broom` accepts that (I guess very likely not but.. who knows), but extra information could be put into an additional attribute ("`extra:fixef`" for instance). This attribute, if present, could then be processed in your package.  This could be extended to estimations from other packages that offer extra relevant information not directly in the base `glance` table. 

Thanks @karldw for all the work on the PR. Your code is very clear, and it's close to final stage I guess! 

Regarding implementation directly in `fixest` using `generics`: well, I'm still not super in favor, but let me ponder that!

**Comment by vincentarelbundock** [comment] 2020-06-01 15:03
Thanks for your answer and for the suggestion. `generics` is a pretty light dependency, but I totally understand if you prefer not to integrate. In any case, support in `broom` would be enough for me.

Thanks for your work on a great package.

Feel free to close this issue once you make a decision.

**Comment by lrberge** [comment] 2020-06-03 15:18
Actually `generics` wouldn't be enough, because a `tibble` should be returned to comply with `broom`'s standard. So that's really a no go for me, sorry.
But I really think `broom` compatibility is important. In my opinion, the major issue with R (as opposed to eg Stata) is the lack of integration of statistical methods (my package is no exception). Since packages are written in an uncoordinated way, the only solution is to force to some sorts of standardization, and broom does exactly that. 
Please @karldw, let me know if there is anything I can do to help for the PR you've written.

@vincentarelbundock : I wasn't familiar with your package, and I'm quite impressed by the variety of output it offers and all the customization possibilities, it looks great!
To continue on the fixed-effects line (and possibly the nber of FE units per regression). I think it's an important information to be reported and I had to develop my own way of doing Latex exports to incorporate that information (the function `etable`). Yet it's highly inadequate since i) it's not as customizable as your functions (bc it wasn't the point), and ii) it's not compatible with estimations from other models.  
It would be great if we could find a way to incorporate the FEs information in your package, ideally via `broom`.  If I'm not mistaken, adding attributes seems to be a valid way: https://github.com/tidymodels/broom/issues/491
Suggestions for incorporation:

 - within your package, you could catch all attributes starting with "`extra:`" (eg. `extra:fixef`). Then add one or several lines associated to that information.

 - the location of this line(s) in the table could be given by the user using the key after extra (here `fixef`).

 - The exact format of the attribute is to be defined (I was thinking to a named list since it's quite flexible).

 - I think the processing in your package can be done in such a general way that you can provide developers guidelines on how to add extra information in their models, so that it would be automatically integrated within your package. 

Let me know if I can help!

**Comment by vincentarelbundock** [comment] 2020-06-03 15:56
I was probably thinking about the `tidy` function implemented for `lm_robust` in the `estimatr` package, which returns a dataframe: 

https://github.com/DeclareDesign/estimatr/blob/master/R/S3_tidy.R

But you're right. This is probably not 100% standards compliant.

Thanks for checking out `modelsummary`! It's still a very new package under active development. Just in the last couple days I added support for several new output formats like MS Word and `flextable`.

I agree that attributes would be a very clean way to achieve this. But I grep-ed through the `broom` repo and couldn't a single tidier which makes use of attributes. I'm not sure `modelsummary` has enough clout yet to enforce new standards on the community ;)

Until there's a more concerted push in the community toward attributes in `tidy` output, I'm not sure it makes sense for you to do much on that front.

One stopgap solution for `modelsummary` could be to define a `glance_extra.fixest` method which adds extra info to `glance.fixest` whenever available. In your case, all the info is already available from the model object, so there would be no change needed in `fixest`.

Incidentally, this would allow users to customize their models more easily. Right now, the recommended approach is to define a custom model class, but that's pretty cumbersome: 

https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html#customizing-existing-models-1

**Comment by karldw** [comment] 2020-06-04 17:53
@lrberge, got it! I think it's up to _broom_ developers at this point. Time is always a challenge when (as far as I know) they don't have any full-time staff.

**Comment by lrberge** [comment] 2020-06-06 12:05
Fantastic! Thanks for the work everyone!
I'm closing the issue then.

**Closed by lrberge** 2020-06-06 12:05 UTC

**Comment by vincentarelbundock** [comment] 2020-06-14 00:03
FYI, I just added a new mechanism to `modelsummary` that allows users to extract additional information from models. Even if the list of fixed effects is not extracted by `broom`, you can add the to a table automatically by defining a simple `glance_custom.fixest` method. I included a `fixest` example in the package documentation here: 

https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html#fixed-effects-regression-1

For instance, you can produce Markdown, LaTeX or MS-Word Fixest tables like this:

``` r
library(fixest)
library(modelsummary)

# custom method to extract fixed effects terms
glance_custom.fixest <- function(x) {
    out <- tibble::tibble(.rows = 1)
    for (n in x$fixef_vars) {
        out[[paste('FE: ', n)]] <- 'X'
    }
    return(out)
}

# Download data and fit models
url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/plm/EmplUK.csv'
dat <- read.csv(url)
mod <- list()
mod[[1]] <- feols(emp ~ wage, dat)
mod[[2]] <- feols(emp ~ wage | firm, dat)
mod[[3]] <- feols(emp ~ wage | firm + year, dat)

# Markdown table
msummary(mod, 'markdown')

|            |Model 1   |Model 2   |Model 3   |
|:-----------|:---------|:---------|:---------|
|(Intercept) |15.228    |          |          |
|            |(2.149)   |          |          |
|wage        |-0.307    |-0.137    |-0.062    |
|            |(0.087)   |(0.065)   |(0.054)   |
|Num.Obs.    |1031      |1031      |1031      |
|R2          |0.012     |0.981     |0.983     |
|R2 Adj.     |0.011     |0.978     |0.980     |
|R2 Within   |          |0.016     |0.003     |
|AIC         |8625.3    |4825.0    |4751.9    |
|BIC         |8649.0    |6499.5    |6521.5    |
|Log.Lik.    |-4310.633 |-2271.475 |-2226.949 |
|FE:  firm   |          |X         |X         |
|FE:  year   |          |          |X         |


# LaTeX table
msummary(mod, 'latex')

\begin{table}[H]
\centering
\begin{tabular}{llll}
\toprule
        & Model 1 & Model 2 & Model 3\\
\midrule
(Intercept) & 15.228 &  & \\
 & (2.149) &  & \\
wage & -0.307 & -0.137 & -0.062\\
 & (0.087) & (0.065) & (0.054)\\
\midrule
Num.Obs. & 1031 & 1031 & 1031\\
R2 & 0.012 & 0.981 & 0.983\\
R2 Adj. & 0.011 & 0.978 & 0.980\\
R2 Within &  & 0.016 & 0.003\\
AIC & 8625.3 & 4825.0 & 4751.9\\
BIC & 8649.0 & 6499.5 & 6521.5\\
Log.Lik. & -4310.633 & -2271.475 & -2226.949\\
FE:  firm &  & X & X\\
FE:  year &  &  & X\\
\bottomrule
\end{tabular}
\end{table}

# MS-Word Table
msummary(mod, 'table.docx')
```


<sup>Created on 2020-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
