### ISSUE TITLE
Bug in predict method when using scale in model formula

### ISSUE THREAD

**Issue by steffengreup** [lrberge/fixest#200] opened 2021-09-29 15:02 UTC
Hi,

I believe I encountered a bug in the predict method. It occurs when the function 'scale' was used in the model formula. 

Example:

``` r

library(fixest)

mod_stats  <- lm(mpg ~ scale(wt), data = mtcars)
mod_fixest <- feols(mpg ~ scale(wt), data = mtcars)

new_data <- data.frame(wt = 3)

predict(mod_stats, newdata = new_data)
#>        1 
#> 21.25171
predict(mod_fixest, newdata = new_data)
#> [1] NaN
```

<sup>Created on 2021-09-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lrberge** [comment] 2021-09-29 20:18
Hi! And a bug it is indeed!

I don't use R's built-in method to create the data for performance reasons, but it has drawbacks and this is one of them. 
The problem is general and exists for any function in the formula that requires the full distribution of the data  to be correctly evaluated (like `scale`, `poly`, `spline` and maybe others).

I've dealt with this issue for `poly` (see #109), but the way I solved it was really complicated. So I'll try to find a more general way to solve this problem.

Thanks for reporting!

**Comment by lrberge** [comment] 2021-09-30 20:12
Fixed in the current dev:
```R
mod_fixest <- feols(mpg ~ scale(wt), data = mtcars)
new_data <- data.frame(wt = 3)
predict(mod_fixest, newdata = new_data)
#> [1] 21.25171
```

**Closed by lrberge** 2021-09-30 20:12 UTC
