### ISSUE TITLE
demean error message

### ISSUE THREAD

**Issue by shoonlee** [lrberge/fixest#46] opened 2020-10-04 18:46 UTC
Hi! Thanks for the great package! I'm using ```demean``` function for my analysis and I think it works fine but throws some random error message that changes every time (or sometimes not even showing up). Practically, when I implement this within ```Rmarkdown``` it stops the compiling so as a get-around I save it to a separate file using R script and load the data into the ```rmd``` but obviously this is not the most efficient way. Here's a reproducible example, which is a subset of my actual data.

```
test <- structure(list(ln_dmg = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8.59600720786391, 
0, 9.71410729937478, 0, 0, 12.1270302478998, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10.2449188370322, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 7.60692111895402, 0, 0, 0, 0, 0, 0, 0, 0, 
0), comm_id = c("060001", "060001", "060001", "060001", "060001", 
"060001", "060001", "060001", "060001", "060001", "060001", "060001", 
"060001", "060001", "060001", "060001", "060001", "060001", "060001", 
"060001", "060001", "060001", "060001", "060001", "060001", "060002", 
"060002", "060002", "060002", "060002", "060002", "060002", "060002", 
"060002", "060002", "060002", "060002", "060002", "060002", "060002", 
"060002", "060002", "060002", "060002", "060002", "060002", "060002", 
"060002", "060002", "060002", "060003", "060003", "060003", "060003", 
"060003", "060003", "060003", "060003", "060003", "060003", "060003", 
"060003", "060003", "060003", "060003", "060003", "060003", "060003", 
"060003", "060003", "060003", "060003", "060003", "060003", "060003", 
"060004", "060004", "060004", "060004", "060004", "060004", "060004", 
"060004", "060004", "060004", "060004", "060004", "060004", "060004", 
"060004", "060004", "060004", "060004", "060004", "060004", "060004", 
"060004", "060004", "060004", "060004"), trans_year = c(1983, 
1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 
1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 
2006, 2007, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 
1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 
2003, 2004, 2005, 2006, 2007, 1983, 1984, 1985, 1986, 1987, 1988, 
1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 
2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 1983, 1984, 1985, 
1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 
1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007
), event_id = c(9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 
9999, 9999, 949, 9999, 968, 9999, 9999, 611, 9999, 9999, 9999, 
9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 
9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 611, 
9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 
9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 
9999, 9999, 611, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 
9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 
949, 9999, 9999, 9999, 9999, 611, 9999, 9999, 9999, 9999, 9999, 
9999, 9999, 9999, 9999)), row.names = c(NA, -100L), class = "data.frame")
```
```
Y_demean = fixest::demean(X = test[, "ln_dmg"],
                          fe = test[, c("comm_id", "trans_year", "event_id")])
Warning: stack imbalance in '=', 2 then -9
Error in (function (env, objName, computeSize = TRUE)  : 
  R_Reprotect: only 2 protected items, can't reprotect index -3
```

As mentioned earlier, the error message changes each time I run this code. Here are a few of them. As you can see, sometimes it runs without any error message. Oh and importantly, they produce the same results though. 
```
> Y_demean = fixest::demean(X = test[, "ln_dmg"],
+                           fe = test[, c("comm_id", "trans_year", "event_id")])
Warning: stack imbalance in '=', 2 then -8
Error in (function (env, objName, computeSize = TRUE)  : 
  R_Reprotect: only 3 protected items, can't reprotect index -2
> Y_demean = fixest::demean(X = test[, "ln_dmg"],
+                           fe = test[, c("comm_id", "trans_year", "event_id")])
> Y_demean = fixest::demean(X = test[, "ln_dmg"],
+                           fe = test[, c("comm_id", "trans_year", "event_id")])
Warning: stack imbalance in '=', 2 then 5
> Y_demean = fixest::demean(X = test[, "ln_dmg"],
+                           fe = test[, c("comm_id", "trans_year", "event_id")])
Warning: stack imbalance in '=', 2 then 1
```

I would have ignored this if it wasn't for ```rmd``` so this is not as important issue for others (esp who don't use ```rmd```) but thought that it wouldn't hurt to report. Please let me know any other info is needed. Thanks!!

**Comment by lrberge** [comment] 2020-10-05 08:05
Thanks for the report and the replicable example! 
I've never seen this warning before. And it's a tricky one, hard to get rid off!

It's because of the parallel section of the code when I transform the IDs as integers. To solve the problem, I may have to rewrite entire sections -- so that's not instantaneous.., 

As a short-run fix, just use `nthreads = 1` in the call (`Y_demean = fixest::demean(X = stuff, fe= stuff, nthreads = 1)`).

**Comment by shoonlee** [comment] 2020-10-08 15:33
Thank you so much for the quick fix! Indeed, with ```nthreads == 1```, I don't see the error message anymore. I also found that this error message does not show up on Windows. Maybe this is something specific to MacOS?

**Comment by lrberge** [comment] 2020-10-09 13:35
I'm on Windows and I can make it appear with your example (although I have to put it in a loop: `for(i in 1:50) Y_demean = fixest::demean etc`).

Actually, this message is driving me a bit nuts because it looks somewhat random. Here's what I tried:

 - when calling `feols` => the bug never appears! That's weird because `feols` uses the same C++ functions as in `demean`.

 - when I source all `fixest` code => the bug never appears! That's yet again weird because those are the **exact same functions** as in the package.

I think it's due to the usage of a SEXP object in an OpenMP parallel loop (in [here](https://github.com/lrberge/fixest/blob/master/src/quf.cpp)). Although I use that object only "read-only" and then write only in C++ objects, it might be the cause of the problem (see [this post](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2011-July/002632.html) or [this one](https://stackoverflow.com/questions/37818872/stack-imbalance-while-using-rcppparallel)).... It also might depend on compiler specificities. 

Any help is appreciated! :-)

**Comment by lrberge** [comment] 2020-10-09 15:19
Yes, it seems to come from that SEXP passed around. 

I adapted the code, now I don't see the error any more. Could you check that it does not show up on your computer?

**Comment by shoonlee** [comment] 2020-10-09 17:31
Perfect! It's gone! Thank you so much for your support.

**Comment by lrberge** [comment] 2020-10-12 09:55
Great! Thanks for checking! :-) I'm closing then.

**Closed by lrberge** 2020-10-12 09:55 UTC
