### ISSUE TITLE
Same "keep" argument works on coefplot but not in iplot

### ISSUE THREAD

**Issue by effedp** [lrberge/fixest#284] opened 2022-03-17 15:49 UTC
Hello,

I noticed that the same `regex` behaves differently in `coefplot` and `iplot`. Actually, in the latter case, it doesn't change anything.

Suppose, for example, that I want to estimate an event study using a [-10, 10] window, with -1 as reference year, but I want to plot the [-5,5] windows only.

```R
library(fixest)

estimate = feols(Y ~ 1 + i(toe, -1) | firm + sector^year, panel, cluster="firm")

# Coefplot works properly, but does not print the reference period
coefplot(estimate, keep="toe::-?[0:5]", drop="10")

# Iplot doesn't raise any error, but plots all the coefficients
iplot(estimate, keep="toe::-?[0:5]", drop="10")
```

Am I missing something, or is there some problem? The `fixest' version is the 0.9.0 (not my computer, I need to ask for updates whenever they are needed)

Thank you!

**Comment by grantmcdermott** [comment] 2022-03-18 04:33
Duplicate of #164 I believe (which was fixed in a subsequent release).

**Comment by lrberge** [comment] 2024-02-09 13:25
Hi, the tricky thing is that `iplot` modifies the original variable names in order to render the x-axis correctly (i.e. the x-axis is `-10`, `-9`, etc, `10`, and not `toe::-10`, etc, `toe::10)`. 

So you need to pass the names of the x-axis values, like below:
```R
data(base_did)
est_did = feols(y ~ x1 + i(period, treat, 5) | id + period, base_did)
iplot(est_did, keep = "[3-8]")
```

![image](https://github.com/lrberge/fixest/assets/43536394/e75cb539-6dd8-475b-b57e-6f6e6ce1e1c7)

This isn't really clear and I tried to improve the error message to make it clear what to select:
```R
# The code above errors with full variable names
iplot(est_did, keep = "period::[3-8]")
#> Error: in iplot(est_did, keep = "period::[3-8]"): 
#> Argument 'keep' has removed all variables! Didn't you mean to use 'i.select'? 
#> Also note that in `iplot`, the variables names are the **values** that should be in the x-axis.
#> FYI, valid x-axis values are: `1`, `2`, `3`, `4`, `5`, etc.
```

Sorry for the super long delay!

**Closed by lrberge** 2024-02-09 13:25 UTC
