### ISSUE TITLE
Different results with xtreg from Stata?

### ISSUE THREAD

**Issue by yceny** [lrberge/fixest#26] opened 2020-06-27 15:47 UTC
When I tried including one fix effect, I found that feols and xtreg from Stata gave totally different results (the sign of the coefficient is opposite). Can you explain why? Are they using different optimization methods?

**Comment by lrberge** [comment] 2020-06-27 16:35
Hi, this is very unlikely. What is more likely on the other hand is that you didn't use the option `fe` in xtreg.

```
webuse nlswork
xtset idcode
xtreg ln_w age, fe
```

The previous code gives me identical results in R with `feols`.

The default of xtreg is random effects, and it's a different model with different assumptions, so you get different results.
If the problem persists, please send a minimal working example in both R and Stata illustrating the problem.

**Comment by lrberge** [comment] 2020-06-27 16:37
I took the liberty to add a question mark in the title.

**Comment by yceny** [comment] 2020-06-27 17:45
I did include fe in the xtreg. I am interested in the results for three variables: v1, v2, and v1*v2.

In feols, v1 is significantly negative, v2 is significantly positive, v1*v2 is positive but not significant.

In xtreg (while including fe at the end), v1 is significantly negative, v2 is significantly positive, v1 * v2 is significantly positive. 

So the difference is the interaction term. 

I do notice that in xtreg, it is using t statistics, but in feols, it is z statistics. Could this be the reason?

**Comment by lrberge** [comment] 2020-06-27 20:26
Is it still about the value of the coefficients, as initially asked? I'm sorry, but it is very difficult for me to understand because I don't have all the pieces of the puzzle. Could you add your R output and your Stata output as below?

This is what I get when I use interactions in R and Stata:

```r
library(data.table) ; library(fixest)
base = fread("path/webuse.csv")
(est = feols(ln_wage ~ age*ttl_exp | idcode, base))
#> NOTE: 24 observations removed because of NA values (Breakup: LHS: 0, RHS: 24, Fixed-effects: 0).
#> OLS estimation, Dep. Var.: ln_wage
#> Observations: 28,510 
#> Fixed-effects: idcode: 4710
#> Standard-errors: Clustered (idcode) 
#>              Estimate Std. Error  t value  Pr(>|t|)    
#> age         -0.003993   0.001229  -3.2496  0.001157 ** 
#> ttl_exp      0.105139   0.004896  21.4760 < 2.2e-16 ***
#> age:ttl_exp -0.001679   0.000112 -14.9530 < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> Log-likelihood: -3,061.31   Adj. R2: 0.61962 
#> R2-Within: 0.15291 
```

```
webuse nlswork
xtset idcode
xtreg ln_w c.age##c.ttl_exp, fe 

Fixed-effects (within) regression               Number of obs     =     28,510
Group variable: idcode                          Number of groups  =      4,710

R-sq:                                           Obs per group:
     within  = 0.1529                                         min =          1
     between = 0.2448                                         avg =        6.1
     overall = 0.1818                                         max =         15

                                                F(3,23797)        =    1431.90
corr(u_i, Xb)  = 0.0784                         Prob > F          =     0.0000

---------------------------------------------------------------------------------
        ln_wage |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
----------------+----------------------------------------------------------------
            age |  -.0039931   .0008318    -4.80   0.000    -.0056235   -.0023626
        ttl_exp |    .105139   .0034159    30.78   0.000     .0984437    .1118343
                |
c.age#c.ttl_exp |  -.0016787   .0000802   -20.93   0.000    -.0018359   -.0015215
                |
          _cons |   1.480127   .0183156    80.81   0.000     1.444228    1.516027
----------------+----------------------------------------------------------------
        sigma_u |  .37321473
        sigma_e |  .29487201
            rho |  .61567368   (fraction of variance due to u_i)
---------------------------------------------------------------------------------
F test that all u_i=0: F(4709, 23797) = 7.89                 Prob > F = 0.0000
```

The coefficients are identical. The standard-errors are different because by default in `feols` they are clustered (as mentioned in the output). To get the same standard errors:

```r
summary(est, se = "standard")
#> OLS estimation, Dep. Var.: ln_wage
#> Observations: 28,510 
#> Fixed-effects: idcode: 4710
#> Standard-errors: Standard
#>              Estimate Std. Error  t value  Pr(>|t|)    
#> age         -0.003993   0.000832  -4.8002  1.59e-06 ***
#> ttl_exp      0.105139   0.003416  30.7800 < 2.2e-16 ***
#> age:ttl_exp -0.001679   0.000080 -20.9330 < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> Log-likelihood: -3,061.31   Adj. R2: 0.61962 
#> R2-Within: 0.15291 
```

Could you send something similar to illustrate your problem?

**Comment by yceny** [comment] 2020-06-27 21:03
Here are my code and result in R. Note that it is z value not t value

> summary(feols(hard_braking_sum ~ c_adas + c_driving_experience_month + c_adas_de_month + day_mileage  + gmqualty_make + factor(gmqualty_model_yr_nbr) + umf_xref_body_type_desc + umf_xref_prod_seg_size_desc + umf_xref_finc_gbl_trim + engn_size + mth_of_base_wrnty + umf_xref_door_style_desc + factor(month)+ factor(week_day) + factor(day_quarter) | group_id1, reg))
OLS estimation, Dep. Var.: hard_braking_sum
Observations: 5,134,305 
Fixed-effects: group_id1: 17222
Standard-errors: Clustered (group_id1) 
                                        Estimate Std. Error    z value  Pr(>|z|)    
c_adas                                 -0.556914   0.110648  -5.033200  4.82e-07 ***
c_driving_experience_month              0.012012   0.003388   3.545300  0.000392 ***
c_adas_de_month                         0.003728   0.009275   0.401928  0.687737    
day_mileage                             0.088660   0.008248  10.750000 < 2.2e-16 ***


In Stata, here are the code and result.

. xi: xtreg hard_braking_sum c_adas c_driving_experience_month c_adas_de_month day_mileage i.gmqualty_make i.gmqualty_model_yr_nbr i.umf_xref_finc_gbl_trim i.umf_xref_
> body_type_desc i.umf_xref_prod_seg_size_desc i.umf_xref_door_style_desc engn_size mth_of_base_wrnty i.month i.week_day i.day_quarter, fe

--------------------------------------------------------------------------------------------
          hard_braking_sum |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
---------------------------+----------------------------------------------------------------
                    c_adas |  -.5568729   .0118756   -46.89   0.000    -.5801486   -.5335972
c_driving_experience_month |   .0120089   .0007515    15.98   0.000      .010536    .0134818
           c_adas_de_month |   .0037278    .001353     2.76   0.006     .0010761    .0063796
               day_mileage |   .0886596   .0000933   950.11   0.000     .0884767    .0888425

**Comment by lrberge** [comment] 2020-06-28 08:26
Thanks! Now I see a bit better! :-) 

First a comment: As of version 0.5.0 onward, I now use t-stats for `feols`, and for `feglm` with non-Poisson, non-Logit families. This is to comply with the standards. But it's a detail and almost doesn't change anything: it only changes the way the p-value is computed in *small samples* (<100 observations).

Now let's start the detective work.

The model you estimate is complex. It involves many variables, many of which are factors. This leaves room to inconsistent specifications between the two software (for example the variable `gmqualty_make` is treated as a factor in Stata but not in R).

Here's a two steps procedure:
1) First: brute-force check. Instead of using `feols` and `xtreg`, drop the fixed-effects and use `lm` and `reg`. If the two results are identical, then it's likely that there's a problem in `feols`.
2) Given you think it's a `feols` problem from the first step, try to provide a minimal working example (see refs [here](https://en.wikipedia.org/wiki/Minimal_working_example) and [there](https://stackoverflow.com/help/minimal-reproducible-example)). This way you ensure that you really have found a bug, that I can reproduce and then correct. To do that, 1] reduce the sample size (to ensure fast regressions--the bug should be there anyway), 2] prune the number of variables until having the minimum number of variables for which the bug appears.

Once it's done, just share the minimal working example and I'll solve the bug.

I hope that I've convinced you with the `nlswork` example that `feols` is no different from `xtreg, fe`, so if a difference there is, it is by no means general and it would come from a **bug** (which needs to be corrected then) in the specific way you use `feols` .

**Comment by lrberge** [comment] 2020-07-07 14:55
Hello, could you pinpoint the problem eventually?

**Comment by lrberge** [comment] 2020-07-09 08:00
Hi, I'm closing the issue then. If you find the bug, please reopen the issue or create a new one with the type of bug in the title.
Thanks for using in any case!

**Closed by lrberge** 2020-07-09 08:00 UTC
