### ISSUE TITLE
Confidence intervals not showing with tidy() on fe_ols objects

### ISSUE THREAD

**Issue by abduazizR** [lrberge/fixest#328] opened 2022-07-03 17:29 UTC
Hi,

First, I would like to thank you for the awesome package. It's really fascinating. I was following @grantmcdermott lecture on regression models [here](https://raw.githack.com/uo-ec607/lectures/master/08-regression/08-regression.html#fnref4). When I used `conf.int = TRUE`, I got an empty tibble. The same problem is shown [here](https://broom.tidymodels.org/reference/tidy.fixest.html)
![image](https://user-images.githubusercontent.com/61837330/177050826-23551f61-48ae-4f10-8065-3c29f47aa09c.png)

Not sure if I am doing something wrong or it's a bug in the package.

Hope you can help with this. Thank you!

Update: Here is my `sessionInfo()` output
`> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] listviewer_3.0.0   modelsummary_1.0.0 broom_1.0.0        vtable_1.3.3       kableExtra_1.3.4  
 [6] margins_0.3.26     fixest_0.10.4      ivreg_0.6-1        estimatr_0.30.6    hrbrthemes_0.8.0  
[11] forcats_0.5.1      stringr_1.4.0      dplyr_1.0.9        purrr_0.3.4        readr_2.1.2       
[16] tidyr_1.2.0        tibble_3.1.7       ggplot2_3.3.6      tidyverse_1.3.1    mfx_1.2-2         
[21] betareg_3.1-4      MASS_7.3-57        lmtest_0.9-40      zoo_1.8-10         sandwich_3.0-2    
[26] pacman_0.5.1      

loaded via a namespace (and not attached):
  [1] TH.data_1.1-1       colorspace_2.0-3    ellipsis_0.3.2      modeltools_0.2-23   sjlabelled_1.2.0   
  [6] estimability_1.3    parameters_0.18.1   fs_1.5.2            rstudioapi_0.13     listenv_0.8.0      
 [11] farver_2.1.0        flexmix_2.3-18      fansi_1.0.3         mvtnorm_1.1-3       lubridate_1.8.0    
 [16] xml2_1.3.3          codetools_0.2-18    splines_4.2.1       extrafont_0.18      knitr_1.39         
 [21] pkgload_1.3.0       Formula_1.2-4       jsonlite_1.8.0      Rttf2pt1_1.3.10     dbplyr_2.2.1       
 [26] effectsize_0.7.0    compiler_4.2.1      httr_1.4.3          emmeans_1.7.5       backports_1.4.1    
 [31] assertthat_0.2.1    Matrix_1.4-1        fastmap_1.1.0       cli_3.3.0           htmltools_0.5.2    
 [36] tools_4.2.1         coda_0.19-4         gtable_0.3.0        glue_1.6.2          dreamerr_1.2.3     
 [41] tables_0.9.6        Rcpp_1.0.8.3        carData_3.0-5       jquerylib_0.1.4     cellranger_1.1.0   
 [46] vctrs_0.4.1         svglite_2.1.0       nlme_3.1-158        extrafontdb_1.0     insight_0.17.1     
 [51] xfun_0.31           globals_0.15.1      rvest_1.0.2         lifecycle_1.0.1     future_1.26.1      
 [56] scales_1.2.0        hms_1.1.1           parallel_4.2.1      yaml_2.3.5          sass_0.4.1         
 [61] gdtools_0.2.4       stringi_1.7.6       bayestestR_0.12.1   checkmate_2.1.0     rlang_1.0.3        
 [66] pkgconfig_2.0.3     systemfonts_1.0.4   evaluate_0.15       lattice_0.20-45     prediction_0.3.14  
 [71] labeling_0.4.2      htmlwidgets_1.5.4   tidyselect_1.1.2    parallelly_1.32.0   magrittr_2.0.3     
 [76] R6_2.5.1            generics_0.1.2      multcomp_1.4-19     DBI_1.1.3           pillar_1.7.0       
 [81] haven_2.5.0         withr_2.5.0         datawizard_0.4.1    survival_3.3-1      abind_1.4-5        
 [86] nnet_7.3-17         performance_0.9.1   future.apply_1.9.0  modelr_0.1.8        crayon_1.5.1       
 [91] car_3.1-0           utf8_1.2.2          tzdb_0.3.0          rmarkdown_2.14      grid_4.2.1         
 [96] readxl_1.4.0        data.table_1.14.2   reprex_2.0.1        digest_0.6.29       webshot_0.5.3      
[101] xtable_1.8-4        numDeriv_2016.8-1.1 stats4_4.2.1        munsell_0.5.0       viridisLite_0.4.0  
[106] bslib_0.3.1`

**Comment by grantmcdermott** [comment] 2022-07-03 17:54
Hi @abduazizR,

Can you edit your post to include the output of `sessionInfo()`? I can't seem to reproduce the error, so it may be that you need to update your version of **fixest**. Here's what I get using the most recent (dev) version.

``` r
library(fixest)

gravity = feols(log(Euros) ~ log(dist_km) | Origin + Destination + Product + Year, 
                trade)

broom::tidy(gravity, conf.int = TRUE, cluster = c("Product", "Year"))
#> # A tibble: 1 × 7
#>   term         estimate std.error statistic  p.value conf.low conf.high
#>   <chr>           <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 log(dist_km)    -2.17    0.0760     -28.5 3.88e-10    -2.34     -2.00

confint(gravity)
#>                  2.5 %    97.5 %
#> log(dist_km) -2.500781 -1.838971
```

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Also tagging @paulgp since I know that he encountered a similar error with `confint.fixest()` recently.

**Comment by abduazizR** [comment] 2022-07-03 18:10
> Hi @abduazizR,
> 
> Can you edit your post to include the output of `sessionInfo()`? I can't seem to reproduce the error, so it may be that you need to update your version of **fixest**. Here's what I get using the most recent (dev) version.
> 
> ```r
> library(fixest)
> 
> gravity = feols(log(Euros) ~ log(dist_km) | Origin + Destination + Product + Year, 
>                 trade)
> 
> broom::tidy(gravity, conf.int = TRUE, cluster = c("Product", "Year"))
> #> # A tibble: 1 × 7
> #>   term         estimate std.error statistic  p.value conf.low conf.high
> #>   <chr>           <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
> #> 1 log(dist_km)    -2.17    0.0760     -28.5 3.88e-10    -2.34     -2.00
> 
> confint(gravity)
> #>                  2.5 %    97.5 %
> #> log(dist_km) -2.500781 -1.838971
> ```
> 
> Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)
> 
> Also tagging @paulgp since I know that he encountered a similar error with `confint.fixest()` recently.

Thank you for the quick reply. I updated the post and included my sessionInfo output. Thanks!

**Comment by abduazizR** [comment] 2022-07-03 18:17
I think It's working now with me 
I updated the `fixest` package to the dev version 0.10.5
I believe my problem was because I used the latest version on CRAN, which is 0.10.4.

Thank you for helping me with this issue

**Comment by grantmcdermott** [comment] 2022-07-03 18:31
Great! 

Can you close this issue then?

**Closed** 2022-07-03 18:37 UTC
